#!/usr/bin/env bash

function start {
  echo "Creating 192.168.0.10/24 and connecting to Nomad"
  /usr/bin/env ip netns exec nomad sysctl -w net.ipv4.conf.mv0.forwarding=1
  /usr/bin/env ip netns exec nomad sysctl -w net.ipv4.conf.mv0.arp_notify=1
  /usr/bin/env ip netns exec nomad sysctl -w net.ipv4.conf.mv0.arp_announce=2
  /usr/bin/env ip netns exec nomad sysctl -w net.ipv4.conf.mv0.use_tempaddr=0
  /usr/bin/env ip addr add 192.168.0.10/24 brd + dev mv-int
  /usr/bin/env ip netns exec nomad ip address add 192.168.0.11/24 dev mv0
  /usr/bin/env ip netns exec nomad ip address add 192.168.0.12/24 dev mv0
  /usr/bin/env ip netns exec nomad ip address add 192.168.0.13/24 dev mv0
  /usr/bin/env ip route add 192.168.0.11/24 dev mv-int metric 100 table local
  /usr/bin/env ip route add 192.168.0.12/24 dev mv-int metric 100 table local
  /usr/bin/env ip route add 192.168.0.13/24 dev mv-int metric 100 table local
  /usr/bin/env iptables -t nat -A POSTROUTING -s 192.168.0.0/24 -j MASQUERADE

}

function stop {
  echo "Deleting 192.168.0.10/24"
  /usr/bin/env ip netns exec nomad ip address del 192.168.0.11/24 dev mv0
  /usr/bin/env ip netns exec nomad ip address del 192.168.0.12/24 dev mv0
  /usr/bin/env ip netns exec nomad ip address del 192.168.0.13/24 dev mv0
  /usr/bin/env ip route del 192.168.0.11/24 dev mv-int metric 100 table local
  /usr/bin/env ip route del 192.168.0.12/24 dev mv-int metric 100 table local
  /usr/bin/env ip route del 192.168.0.13/24 dev mv-int metric 100 table local
  /usr/bin/env ip address del 192.168.0.10/24 dev mv-int
  /usr/bin/env iptables -t nat -D POSTROUTING -s 192.168.0.0/24 -j MASQUERADE

}

case "$1" in
   start)
      start
   ;;
   stop)
      stop
   ;;
   restart)
      stop
      start
   ;;
   *)
      echo "Usage: $0 {start|stop|restart}"
esac