#!/usr/bin/env bash

function start {
  echo "Configuring server2 namespace"
  echo "Done"
}

function stop {
  echo "Removing server2 namespace configuration"
  echo "Done"
}

case "$1" in
   start)
      start
   ;;
   stop)
      stop
   ;;
   restart)
      stop
      start
   ;;
   *)
      echo "Usage: $0 {start|stop|restart}"
esac